{ exec } = require 'child_process'

PRODUCT  = "CafeTownsend"
VERSION  = "v0.10.6"
#FILENAME = "#{ PRODUCT }-#{ VERSION }"
FILENAME = "#{ PRODUCT }"

OUTPUT_PATH = "../js/build"

# TODO: Remove - temporarily added until next build of coffee-script is released.
PATH = "/usr/local/bin"

task "build", "Builds #{ PRODUCT } JavaScript (and minified JavaScript) implementation from CoffeeScript source code", ->
	console.log "Building #{ PRODUCT } version #{ VERSION }"
	console.log "Compiling CafeTownsend **.coffee to #{ OUTPUT_PATH }/#{ FILENAME }.js"
	exec "#{ PATH }/coffee --join #{ FILENAME }.js --output #{ OUTPUT_PATH } --bare  --compile ./services.coffee ./controllers.coffee ./directives.coffee", ( error, stdout, stderr ) ->
		console.log stdout + stderr if stdout or stderr
		if error
			throw error
		else
			console.log "Minifying #{ OUTPUT_PATH }/#{ FILENAME }.js to #{ OUTPUT_PATH }/#{ FILENAME }.min.js"
			exec "closure --js #{ OUTPUT_PATH }/#{ FILENAME }.js --js_output_file #{ OUTPUT_PATH }/#{ FILENAME }.min.js", ( error, stdout, stderr ) ->
				console.log stdout + stderr if stdout or stderr
				throw error if error

task "build-document-scripts", "Builds #{ PRODUCT } document script JavaScript implementation(s) from CoffeeScript source code", ->
	console.log "Building #{ PRODUCT } document scripts"
	console.log "Compiling *.coffee to #{ OUTPUT_PATH }/*.js"
	exec "#{ PATH }/coffee --output #{ OUTPUT_PATH } --compile *.coffee", ( error, stdout, stderr ) ->
		console.log stdout + stderr if stdout or stderr
		if error
			throw error
		# TODO: minify